name: PR Validation

on:
  pull_request:
    paths:
      - "Casks/**"
      - ".github/workflows/pr-validation.yml"

permissions: {}

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      casks: ${{ steps.changed.outputs.casks }}
      has_cask_changes: ${{ steps.changed.outputs.has_cask_changes }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Get changes
        id: changed
        run: |
          # Detect changed casks
          CASKS=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- 'Casks/*.rb' | xargs -I{} basename {} .rb)
          if [ -z "$CASKS" ]; then
            echo "No cask changes detected"
            echo "has_cask_changes=false" >> $GITHUB_OUTPUT
            echo "casks=[]" >> $GITHUB_OUTPUT
          else
            JSON_ARRAY=$(echo "$CASKS" | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "Changed casks: $JSON_ARRAY"
            echo "has_cask_changes=true" >> $GITHUB_OUTPUT
            echo "casks=$JSON_ARRAY" >> $GITHUB_OUTPUT
          fi

  validate-cask:
    name: Validate Cask (${{ matrix.cask }})
    runs-on: macos-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.has_cask_changes == 'true'
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        cask: ${{ fromJson(needs.detect-changes.outputs.casks) }}
    env:
      TAP_PATH: ${{ github.repository_owner }}/homebrew-tap
      CASK_PATH: ${{ github.repository_owner }}/homebrew-tap/${{ matrix.cask }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Tap this repository
        run: |
          ABS_TAP_PATH="$(brew --repository)/Library/Taps/${TAP_PATH}"
          mkdir -p "$ABS_TAP_PATH"
          cp -r . "$ABS_TAP_PATH"
      
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ vars.DOCKER_READ_APP_ID }}
          private-key: ${{ secrets.DOCKER_READ_APP_PRIVATE_KEY }}
          owner: docker
          repositories: |
            dash-releases

      - name: Validate cask
        uses: ./validate-cask
        with:
          cask-path: ${{ env.CASK_PATH }}
          tap-path: ${{ env.TAP_PATH }}
          github-token: ${{ steps.app-token.outputs.token }}
